# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
  description = "A Cloud Native Buildpack that builds Clojure applications from source"
  homepage = "https://github.com/paketo-buildpacks/clojure-tools"
  id = "paketo-buildpacks/clojure-tools"
  keywords = ["java", "clojure", "build-system"]
  name = "Paketo Clojure Tools Buildpack"
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/clojure-tools/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "-X:uberjar"
    description = "the arguments to pass to Clojure"
    name = "BP_CLJ_DEPS_ARGUMENTS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "the arguments to enable Tools Build"
    name = "BP_CLJ_TOOLS_BUILD_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "-T:build uber"
    description = "the arguments to pass to Tools Build"
    name = "BP_CLJ_TOOLS_BUILD_ARGUMENTS"

  [[metadata.configurations]]
    build = true
    default = "target/*.jar"
    description = "the built application artifact explicitly. Supersedes $BP_CLJ_BUILT_MODULE"
    name = "BP_CLJ_BUILT_ARTIFACT"

  [[metadata.configurations]]
    build = true
    description = "the module to find application artifact in"
    name = "BP_CLJ_BUILT_MODULE"

  [[metadata.dependencies]]
    id = "clojure"
    name = "Clojure"
    sha256 = "f2a271d6892fb04f7377148f6770185486ca194245721ab34a62ae03e8d1149f"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://download.clojure.org/install/linux-install-1.10.3.986.sh"
    version = "1.10.3"

    [[metadata.dependencies.licenses]]
      type = "Eclipse Public License - v 1.0"
      uri = "https://github.com/clojure/clojure/blob/master/epl-v10.html"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
