# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
id       = "paketo-buildpacks/clojure"
name     = "Paketo Clojure Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/clojure"
description = "A Cloud Native Buildpack that builds Clojure applications from source"
keywords    = ["java", "clojure", "build-system"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/clojure/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.configurations]]
name        = "BP_DEPS_ARGUMENTS"
description = "the arguments to pass to Clojure"
default     = "-X:uberjar"
build       = true

[[metadata.configurations]]
name        = "BP_TOOLS_BUILD_ARGUMENTS"
description = "the arguments to pass to Tools Build"
default     = "-T:build uber"
build       = true

[[metadata.configurations]]
name        = "BP_CLOJURE_BUILT_ARTIFACT"
description = "the built application artifact explicitly.  Supersedes $BP_CLOJURE_BUILT_MODULE"
default     = "target/*.jar"
build       = true

[[metadata.configurations]]
name        = "BP_CLOJURE_BUILT_MODULE"
description = "the module to find application artifact in"
build       = true

[[metadata.dependencies]]
id      = "clojure"
name    = "Clojure"
version = "1.10.3"
uri    = "https://download.clojure.org/install/linux-install-1.10.3.943.sh"
sha256 = "f1fdb786fa8b9ef3a08d0b331a51861cd5a6eea277e93bbad64bf37774df17c6"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "org.cloudfoundry.stacks.cflinuxfs3" ]

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
